export default [{
  id: 'suma04', 
  title: 'Cybersecurity Developer and Analyst',
  company: 'SUMA F2F SL',
  description: 'Development and debugging of web platforms. Identification and mitigation of cybersecurity vulnerabilities.',
  logo: '/images/logos/Logo_Sumaf2f.png',
  commencement: 'Mar 2024',
  termination: 'Present',
}, {
  id: 'ermitagemuscial04', 
  title: 'Cybersecurity Consultant',
  company: 'Ermitage Musical SL',
  description: 'Risk assessment, implementation of proactive security measures and incident response.',
  logo: '/images/logos/Logo_ErmitageMusical.png',
  commencement: 'Aug 2023',
  termination: 'Mar 2024',
}, {
  id: 'ayuntamiento04', 
  title: 'Webmaster Technician',
  company: 'Pedrezuela City Council',
  description: 'Development, maintenance and cybersecurity enhancements for Pedrezuela City Council official website and other internal projects.',
  logo: '/images/logos/Logo_Pedrezuela.png',
  commencement: 'Jul 2022',
  termination: 'Jul 2023',
}, {
  id: 'soporte03', 
  title: 'Support Technician',
  company: 'BeDataScience',
  description: 'Support to the team by integrating into the dashboard design, security, updating and sending final information to the client.',
  logo: '/images/logos/Logo_BDS.png',
  commencement: 'Dec 2021',
  termination: 'Jan 2022',
}, {
  id: 'fct02', 
  title: 'Mobile Application Developer',
  company: 'KUBUS S.A.',
  description: 'Development of a mobile app for orders, testing, fixing bugs and API connection.',
  logo: '/images/logos/Logo_KubusSA.png',
  commencement: 'Apr 2021',
  termination: 'Oct 2021',
}];