export default [{
  id: 'ayuntamiento04', 
  title: 'Webmaster Technician',
  company: 'Pedrezuela City Council',
  description: 'Development, maintenance and cybersecurity enhancements for Pedrezuela City Council official website and other internal projects.',
  logo: '/images/logos/Logo_Pedrezuela.png',
  commencement: 'July 2022',
  termination: 'July 2023',
}, {
  id: 'soporte03', 
  title: 'Support Technician',
  company: 'BeDataScience',
  description: 'Support to the team by integrating into the dashboard design, security, updating and sending final information to the client.',
  logo: '/images/logos/Logo_BDS.png',
  commencement: 'December 2021',
  termination: 'January 2022',
}, {
  id: 'fct02', 
  title: 'Mobile Application Developer',
  company: 'KUBUS S.A.',
  description: 'Development of a mobile app for orders, testing, fixing bugs and API connection.',
  logo: '/images/logos/Logo_KubusSA.png',
  commencement: 'April 2021',
  termination: 'October 2021',
}];