export default [{
  id: 'suma04', 
  title: 'Desarrollador y Analista de Ciberseguridad',
  company: 'SUMA F2F SL',
  description: 'Desarrollo de código para plataformas web. Identificación y mitigación de vulnerabilidades de ciberseguridad.',
  logo: '/images/logos/Logo_Sumaf2f.png',
  commencement: 'Abril 2024',
  termination: 'Actualidad',
}, {
  id: 'ayuntamiento04', 
  title: 'Técnico Webmaster',
  company: 'Ayuntamiento de Pedrezuela',
  description: 'Desarrollo, mantenimiento y mejoras en la ciberseguridad de la página web oficial del Ayuntamiento de Pedrezuela y otros proyectos.',
  logo: '/images/logos/Logo_Pedrezuela.png',
  commencement: 'Julio 2022',
  termination: 'Julio 2023',
}, {
  id: 'soporte03', 
  title: 'Técnico de Soporte',
  company: 'BeDataScience',
  description: 'Soporte al equipo integrándose en el diseño de cuadro de mando, seguridad, actualización y envío de información final al cliente.',
  logo: '/images/logos/Logo_BDS.png',
  commencement: 'Diciembre 2021',
  termination: 'Enero 2022',
}, {
  id: 'fct02', 
  title: 'FCT Desarrollador de Aplicaciones Móviles',
  company: 'KUBUS S.A.',
  description: 'Desarrollo de app móvil para pedidos, pruebas, corrección de errores y conexión API.',
  logo: '/images/logos/Logo_KubusSA.png',
  commencement: 'Abril 2021',
  termination: 'Octubre 2021',
}];