export default [{
  id: 'ayuntamiento04', 
  title: 'Técnico Webmaster',
  company: 'Ayuntamiento de Pedrezuela',
  description: 'Desarrollo, actualización y mantenimiento de la nueva página web oficial del Ayuntamiento de Pedrezuela y otros proyectos internos.',
  logo: '/images/logos/Logo_Pedrezuela.png',
  commencement: 'Julio 2022',
  termination: 'Julio 2023',
}, {
  id: 'soporte03', 
  title: 'Técnico de Soporte',
  company: 'BeDataScience',
  description: 'Soporte al equipo integrándose en el diseño de cuadro de mando, actualización y envío de información final al cliente.',
  logo: '/images/logos/Logo_BDS.png',
  commencement: 'Diciembre 2021',
  termination: 'Enero 2022',
}, {
  id: 'fct02', 
  title: 'FCT Desarrollador de Aplicaciones Móviles',
  company: 'KUBUS S.A.',
  description: 'Desarrollador de apps móviles y APIs.',
  logo: '/images/logos/Logo_KubusSA.png',
  commencement: 'Abril 2021',
  termination: 'Junio 2021',
}];