export default [{
  id: 'suma04', 
  title: 'Desarrollador y Analista de Ciberseguridad',
  company: 'SUMA F2F SL',
  description: 'Desarrollo y depuración de plataformas web. Identificación y mitigación de vulnerabilidades de ciberseguridad.',
  logo: '/images/logos/Logo_Sumaf2f.png',
  commencement: 'Mar 2024',
  termination: 'Actualidad',
}, {
  id: 'ermitagemuscial04', 
  title: 'Consultor de Ciberseguridad',
  company: 'Ermitage Musical SL',
  description: 'Evaluación de riesgos, implementación de medidas de seguridad proactivas y respuesta a incidentes.',
  logo: '/images/logos/Logo_ErmitageMusical.png',
  commencement: 'Aug 2023',
  termination: 'Mar 2024',
}, {
  id: 'ayuntamiento04', 
  title: 'Técnico Webmaster',
  company: 'Ayuntamiento de Pedrezuela',
  description: 'Desarrollo, mantenimiento y mejoras en la ciberseguridad de la página web oficial del Ayuntamiento de Pedrezuela y otros proyectos.',
  logo: '/images/logos/Logo_Pedrezuela.png',
  commencement: 'Jul 2022',
  termination: 'Jul 2023',
}, {
  id: 'soporte03', 
  title: 'Técnico de Soporte',
  company: 'BeDataScience',
  description: 'Soporte al equipo, seguridad, actualización y envío de información final al cliente.',
  logo: '/images/logos/Logo_BDS.png',
  commencement: 'Dic 2021',
  termination: 'Ene 2022',
}, {
  id: 'fct02', 
  title: 'FCT Desarrollador de Aplicaciones Móviles',
  company: 'KUBUS S.A.',
  description: 'Desarrollo de app móvil para pedidos, pruebas, corrección de errores y conexión API.',
  logo: '/images/logos/Logo_KubusSA.png',
  commencement: 'Abr 2021',
  termination: 'Oct 2021',
}];