export default [{
  id: 'liana01', 
  title: "Modelo Portfolio",
  description: 'Actualmente trabajando en un portfolio web para modelo.',
  image: '/images/projects/PortfolioLiana.png',
  development: 'Desarrollada en: React y Bootstrap 5',
  urlGitHub: 'https://github.com/DRAKONNN/PortfolioLiana',
  url: 'https://liana-unanyan.netlify.app/',
  classAttBackgroundText: 'bg-white text-danger',
  classAttButton: 'btn-dark text-white',
}, {
  id: 'mt01', 
  title: "Mystery-Tales",
  description: 'Proyecto web personal sobre historias de detectives y acertijos.',
  image: '/images/projects/MysteryTales.png',
  development: 'Desarrollada en: React y Bootstrap 5',
  urlGitHub: 'https://github.com/DRAKONNN/MysteryTales',
  url: 'https://mysterytales.netlify.app/',
  classAttBackgroundText: 'bg-dark text-warning',
  classAttButton: 'btn-dark text-white',
}, {
  id: 'stacko01', 
  title: "STACK'O",
  description: 'Proyecto personal de una página web para filtrar diferentes juegos de cartas dependiendo del filtro que se necesite.',
  image: '/images/projects/StackoLinkedin.png',
  development: 'Desarrollada en: React y Bootstrap 5',
  urlGitHub: 'https://github.com/DRAKONNN/STACK-O',
  url: 'https://stack-o.netlify.app/',
  classAttBackgroundText: 'bg-primary text-white',
  classAttButton: 'btn-dark text-white',
}, {
  id: 'agz27', 
  title: "Arganzuela 27",
  description: 'TFG: app móvil que mejora la organización de un colectivo solidario',
  image: '/images/projects/PlayStoreAgz27.png',
  development: 'Desarrollada en: Android Studio, PHP y SQL',
  urlGitHub: 'https://github.com/DRAKONNN',
  url: 'https://play.google.com/store/apps/details?id=com.proyecto_agz.proyecto_agz',
  classAttBackgroundText: 'bg-dark text-white',
  classAttButton: 'btn-light text-dark',
}];