export default [{
  id: 'stacko01', 
  title: "STACK'O",
  description: 'Proyecto personal de una página web para filtrar diferentes juegos de cartas dependiendo del filtro que se necesite.',
  image: '/images/projects/StackoLinkedin.png',
  development: 'Desarrollada en: React y Bootstrap 5',
  urlGitHub: 'https://github.com/DRAKONNN/stacko',
  url: 'https://stackoproject.netlify.app/',
  classAttBackgroundText: 'bg-primary text-white',
  classAttButton: 'btn-dark text-white',
}, {
  id: 'agz27', 
  title: "Arganzuela 27",
  description: 'TFG: app móvil que mejora la organización de un colectivo solidario',
  image: '/images/projects/PlayStoreAgz27.png',
  development: 'Desarrollada en: Android Studio, PHP y SQL',
  urlGitHub: 'https://github.com/DRAKONNN',
  url: 'https://play.google.com/store/apps/details?id=com.proyecto_agz.proyecto_agz',
  classAttBackgroundText: 'bg-dark text-white',
  classAttButton: 'btn-light text-dark',
}];